services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - APP_PORT=8080
    volumes:
      # Mount configs directory for environment variables
      - ./configs:/root/configs:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/stations"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
